llm:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
  groq:
    provider: "groq"
    model_name: "llama-3.1-8b-instant"
  gemini:
    provider: "gemini"
    model_name: "gemini-2.0-flash"